# Form implementation generated from reading ui file 'pinDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(185, 59)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color:rgb(242, 242, 242);\n"
"color: rgb(56, 56, 56);\n"
"font: 24pt \"Arial\";\n"
"")
        self.lb_time = QtWidgets.QLabel(parent=Dialog)
        self.lb_time.setGeometry(QtCore.QRect(40, 0, 145, 60))
        self.lb_time.setObjectName("lb_time")
        self.lb_time.setStyleSheet("qproperty-alignment: \'AlignCenter\'")
        self.pin_start = QtWidgets.QPushButton(parent=Dialog)
        self.pin_start.setGeometry(QtCore.QRect(0, 10, 45, 41))
        self.pin_start.setStyleSheet("border: 0px")
        self.pin_start.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("qrc/start.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pin_start.setIcon(icon1)
        self.pin_start.setIconSize(QtCore.QSize(32, 32))
        self.pin_start.setObjectName("pin_start")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "EyeCare"))
        self.lb_time.setText(_translate("Dialog", "00:20:00"))
